import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { DISCOVERY_DOMAINS, DISCOVERY_LIMITS, verifyMeshAdvertisement, safeGatewayOrigin, verifyEndpoint, EndpointCache,
  createBrowserIdentity, signBrowserRecord, verifyBrowserRecord, signSignal, verifySignal, signChallenge, verifyChallenge } from '../public/mesh-discovery.js';
import { fixtureIdentity, fixtureNetwork as network, fixtureNow as now, meshAdvertisement, endpointAdvertisement, signDiscoveryRaw } from './mesh-signing-fixtures.mjs';
const errorCode = code => error => error?.code === code;
const identity = fixtureIdentity(), other = fixtureIdentity(2);
const fields = (overrides = {}) => ({ network, sessionId: '11'.repeat(16), browserId: '22'.repeat(16), nodeId: identity.nodeId,
  sourceId: 'common-a', rendezvous: ['https://gateway.example.org'], issuedAt: now, expiresAt: now + 120000, ...overrides });
const browser = (overrides = {}, key = identity) => signBrowserRecord(fields(overrides), key);
const signalPayload = (overrides = {}) => ({ version: 1, network, from: identity.peerId, to: other.peerId, fromSessionId: '11'.repeat(16), toSessionId: '33'.repeat(16),
  seq: 1, type: 'offer', value: 'v=0\r\na=ice-options:trickle\r\n', issuedAt: now, expiresAt: now + 30000, ...overrides });
const decode = envelope => JSON.parse(Buffer.from(envelope.payloadBase64, 'base64').toString());

test('vendored crypto artifact matches deterministic build provenance and exact pinned package versions', async () => {
  const base = new URL('../public/vendor/', import.meta.url), proof = JSON.parse(await readFile(new URL('mesh-crypto-provenance.json', base)));
  assert.equal(createHash('sha256').update(await readFile(new URL('mesh-crypto.js', base))).digest('hex'), proof.sha256);
  assert.deepEqual(proof.packages.map(p => [p.name, p.version, p.license]), [['@noble/curves', '2.4.0', 'MIT'], ['@noble/hashes', '2.4.0', 'MIT']]);
  assert.equal(DISCOVERY_LIMITS.endpoints, 64); assert.equal(DISCOVERY_LIMITS.rendezvous, 4);
});

test('independent Cypher Go crypto vector verifies exact native signature, recovery ID, Keccak domain and node identity', () => {
  // Generated by Cypher crypto.Sign/crypto.VerifySignature, not by noble. Fixed
  // public test scalar=1. The reproduction source and output are retained in
  // relay/evidence/discovery/; private production/native keys were never read.
  const envelope = meshAdvertisement(identity);
  const signatureHex = 'ac0a3de557837c6a81d01ab8dfcf32cafd5abeaa3ff37283380b67448d2596b57b3d8a42d525c4ea2cc076749bd65fe5649dd07a42bdc3c447aedf282913cb1800';
  assert.equal(envelope.signatureHex, signatureHex, 'deterministic Go and noble signatures match byte for byte');
  const result = verifyMeshAdvertisement({ ...envelope, signatureHex }, network, now);
  assert.equal(result.nodeId, 'c0a6c424ac7157ae408398df7e5f4552091a69125d5dfcb7b8c2659029395bdf');
  assert.throws(() => verifyMeshAdvertisement({ ...envelope, signatureHex: signatureHex.slice(0, -2) + '01' }, network, now), errorCode('invalid_signature'));
});

test('native advertisements authenticate complete signed bytes and reject forged signatures and invalid curve points', () => {
  const env = meshAdvertisement(identity), record = verifyMeshAdvertisement(env, network, now);
  assert.equal(record.publicKey, identity.publicKeyHex);
  const changed = { ...decode(env), expiresAt: now + 110000 };
  assert.throws(() => verifyMeshAdvertisement({ ...env, payloadBase64: Buffer.from(JSON.stringify(changed)).toString('base64') }, network, now), errorCode('invalid_signature'));
  assert.throws(() => verifyMeshAdvertisement(meshAdvertisement(identity, { enode: other.enode }), network, now), errorCode('invalid_signature'));
  assert.throws(() => verifyMeshAdvertisement(meshAdvertisement(identity, { enode: `enode://${'00'.repeat(64)}` }), network, now), errorCode('invalid_signature'));
  const wrongDomain = signDiscoveryRaw(record.raw, identity, DISCOVERY_DOMAINS.endpoint);
  assert.throws(() => verifyMeshAdvertisement(wrongDomain, network, now), errorCode('invalid_signature'));
  assert.throws(() => verifyMeshAdvertisement(signDiscoveryRaw(record.raw, identity, DISCOVERY_DOMAINS.advertisement.slice(0, -1)), network, now), errorCode('invalid_signature'));
  // High-S malleation remains mathematically valid ECDSA but native verification
  // requires low-S. Toggle recovery parity alongside n-S and still reject it.
  const order = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141n;
  const s = BigInt('0x' + env.signatureHex.slice(64, 128));
  const signatureHex = env.signatureHex.slice(0, 64) + (order - s).toString(16).padStart(64, '0') + (env.signatureHex.endsWith('00') ? '01' : '00');
  assert.throws(() => verifyMeshAdvertisement({ ...env, signatureHex }, network, now), errorCode('invalid_signature'));
});

test('fixed endpoint descriptor signed by Go matches the browser exact bytes and signature', () => {
  const envelope = endpointAdvertisement(identity);
  // /root/cypher/node/browserrelay/testdata/mesh-endpoint-vector.json is generated
  // using native crypto.Sign and independently asserted by native meshSignEndpoint.
  const signatureHex = '66f0bd687a5707851429158b2eb08d898e1075482ea54dd2f8fd8cbfa6295136268da3124b7d3856e0b394b82102f2f8f12ae668dea531eee8ee1c4c5f60710a01';
  assert.equal(envelope.signatureHex, signatureHex);
  const record = verifyEndpoint({ ...envelope, signatureHex }, network, now);
  assert.equal(record.nodeId, identity.nodeId); assert.equal(record.payload.sequence, 1);
  assert.equal(record.origin, 'https://gateway.example.org');
});

test('signed payload whitespace stays exact and duplicate decoded keys, null or unknown fields are rejected', () => {
  const payload = decode(endpointAdvertisement()), raw = JSON.stringify(payload, null, 2) + '\n';
  const env = signDiscoveryRaw(raw, identity, DISCOVERY_DOMAINS.endpoint);
  assert.equal(Buffer.from(verifyEndpoint(env, network, now).raw).toString(), raw);
  for (const bad of [raw.replace('"version": 1', '"version": 1,"\\u0076ersion": 1'), JSON.stringify({ ...payload, injected: true }), 'null'])
    assert.throws(() => verifyEndpoint(signDiscoveryRaw(bad, identity, DISCOVERY_DOMAINS.endpoint), network, now));
  assert.throws(() => verifyEndpoint({ ...env, extra: 1 }, network, now));
});

test('public HTTPS origins reject credentials, URL paths, queries, alias encodings, local and special networks', () => {
  for (const valid of ['https://gateway.example.org', 'https://gateway.example.org:8443', 'https://8.8.8.8', 'https://[2606:4700:4700::1111]']) assert.equal(safeGatewayOrigin(valid), valid);
  for (const value of ['http://gateway.example.org', 'wss://gateway.example.org', 'https://gateway.example.org/', 'https://gateway.example.org/path',
    'https://user:secret@gateway.example.org', 'https://gateway.example.org?token=x', 'https://gateway.example.org#fragment', 'https://GATEWAY.example.org',
    'https://gateway.example.org:443', 'https://gateway.example.org:0', 'https://127.0.0.1', 'https://127.1', 'https://2130706433', 'https://0x7f000001', 'https://10.1.2.3',
    'https://192.168.1.1', 'https://172.31.1.1', 'https://169.254.169.254', 'https://100.64.0.1', 'https://0.0.0.0', 'https://224.0.0.1',
    'https://[::1]', 'https://[::ffff:127.0.0.1]', 'https://[fc00::1]', 'https://[fe80::1]', 'https://[2002:7f00:1::1]', 'https://[2001::7f00:1]', 'https://[2001:2::1]', 'https://localhost', 'https://a.local', 'https://a.internal',
    'https://a.home', 'https://a.localhost', 'https://local', 'https://gateway.example.org.', 'https://gateway.example.org\\@127.0.0.1'])
    assert.throws(() => safeGatewayOrigin(value), errorCode('unsafe_origin'), value);
});

test('endpoint claims bind network, identity, source, exact origin, process boot and sequence', () => {
  const env = endpointAdvertisement(), record = verifyEndpoint(env, network, now);
  assert.equal(record.origin, 'https://gateway.example.org'); assert.equal(record.sourceId, 'common-a'); assert.equal(record.nodeId, identity.nodeId);
  assert.throws(() => verifyEndpoint(env, { ...network, chainId: 123 }, now), errorCode('wrong_network'));
  for (const overrides of [{ sequence: 0 }, { sequence: 1.5 }, { sequence: '1' }, { bootId: 'no' }, { sourceId: '../socket' }, { gatewayOrigin: 'https://127.0.0.1' }])
    assert.throws(() => verifyEndpoint(endpointAdvertisement(identity, overrides), network, now));
  const tampered = { ...decode(env), gatewayOrigin: 'https://other.example.org' };
  assert.throws(() => verifyEndpoint({ ...env, payloadBase64: Buffer.from(JSON.stringify(tampered)).toString('base64') }, network, now), errorCode('invalid_signature'));
});

test('endpoint TTL, future-clock skew, raw/envelope bounds are finite', () => {
  const env = endpointAdvertisement(); verifyEndpoint(env, network, now + 119999); verifyEndpoint(env, network, now - 10000);
  for (const clock of [now + 120000, now - 10001]) assert.throws(() => verifyEndpoint(env, network, clock), errorCode('stale_advertisement'));
  for (const overrides of [{ expiresAt: now + 120001 }, { issuedAt: -1 }, { issuedAt: now + 20000 }, { expiresAt: now }])
    assert.throws(() => verifyEndpoint(endpointAdvertisement(identity, overrides), network, now), errorCode('stale_advertisement'));
  const raw = ' '.repeat(4096) + JSON.stringify(decode(env));
  assert.throws(() => verifyEndpoint(signDiscoveryRaw(raw, identity, DISCOVERY_DOMAINS.endpoint), network, now));
});

test('RAM endpoint cache rejects sequence rollback, same-sequence mutation and old-process replay', () => {
  let clock = now; const cache = new EndpointCache(network, { now: () => clock });
  const first = endpointAdvertisement(); const record = cache.add(first); assert.equal(cache.add(first), record);
  cache.add(endpointAdvertisement(identity, { sequence: 2, issuedAt: now + 1 }));
  assert.throws(() => cache.add(first), errorCode('sequence_rollback'));
  assert.throws(() => cache.add(endpointAdvertisement(identity, { sequence: 2, issuedAt: now + 1, gatewayOrigin: 'https://other.example.org' })), errorCode('sequence_rollback'));
  const restarted = endpointAdvertisement(identity, { bootId: '77'.repeat(16), sequence: 1, issuedAt: now + 2 }); cache.add(restarted);
  assert.throws(() => cache.add(endpointAdvertisement(identity, { sequence: 3, issuedAt: now + 3 })), errorCode('sequence_rollback'));
  assert.throws(() => cache.add(endpointAdvertisement(identity, { bootId: '88'.repeat(16), issuedAt: now + 1 })), errorCode('sequence_rollback'));
  assert.equal(cache.values().length, 1); clock = now + 120000; assert.equal(cache.values().length, 0); assert.equal(cache.get(identity.nodeId), undefined);
  clock += 10000; cache.prune(); assert.equal(cache.records.size, 0);
});

test('cache cap rejects new identities without evicting current routes and bounds restart tombstones', () => {
  const cache = new EndpointCache(network, { now: () => now, maxEntries: 1 }); cache.add(endpointAdvertisement());
  assert.throws(() => cache.add(endpointAdvertisement(other)), errorCode('resource_limit')); assert.equal(cache.get(identity.nodeId).sourceId, 'common-a');
  for (let i = 1; i <= 8; i++) cache.add(endpointAdvertisement(identity, { bootId: i.toString(16).padStart(32, '0'), issuedAt: now + i }));
  assert.throws(() => cache.add(endpointAdvertisement(identity, { bootId: '99'.repeat(16), issuedAt: now + 9 })), errorCode('resource_limit'));
  assert.equal(cache.records.get(identity.nodeId).retired.size, 8);
});

test('browser ephemeral identities are random RAM keys; signed records bind key, peer/session and rendezvous', () => {
  const a = createBrowserIdentity(), b = createBrowserIdentity(); assert.notEqual(a.peerId, b.peerId); assert.equal(a.privateKey.length, 32);
  const signed = signBrowserRecord(fields(), a), verified = verifyBrowserRecord(signed, network, now);
  assert.equal(verified.peerId, a.peerId); assert.equal(verified.publicKey, a.publicKeyHex); assert.equal(verified.payload.sessionId, '11'.repeat(16));
  const wrong = { ...decode(signed), peerId: b.peerId };
  assert.throws(() => verifyBrowserRecord(signDiscoveryRaw(JSON.stringify(wrong), a, DISCOVERY_DOMAINS.browser), network, now), errorCode('invalid_signature'));
  for (const overrides of [{ rendezvous: [] }, { rendezvous: Array.from({ length: 5 }, (_, i) => `https://g${i}.example.org`) },
    { rendezvous: ['https://gateway.example.org', 'https://gateway.example.org'] }, { browserId: 'arbitrary-string' }, { sessionId: null }]) assert.throws(() => browser(overrides));
});

test('browser signature does not claim native affiliation and native records cannot become browser records', () => {
  const verified = verifyBrowserRecord(browser({ nodeId: other.nodeId }), network, now);
  assert.equal(verified.nodeId, other.nodeId, 'Native-affiliation claim remains explicitly unauthenticated');
  assert.throws(() => verifyBrowserRecord(endpointAdvertisement(), network, now));
});

test('signed SDP and ICE bind sender generation and recipient; tampered recovery/signature and future/stale records fail', () => {
  const record = browser(), envelope = signSignal(signalPayload(), identity), verified = verifySignal(envelope, record, network, now);
  assert.equal(verified.to, other.peerId); assert.equal(verified.value, signalPayload().value);
  assert.throws(() => verifySignal(envelope, browser({ sessionId: '44'.repeat(16) }), network, now), errorCode('wrong_session'));
  assert.throws(() => verifySignal(envelope, record, network, now + 30000), errorCode('stale_advertisement'));
  assert.throws(() => verifySignal(envelope, browser({}, other), network, now), errorCode('wrong_session'));
  for (const value of [null, { candidate: 'candidate:1 1 udp 1 1.2.3.4 9999 typ host', sdpMid: '0', sdpMLineIndex: 0, usernameFragment: 'ufrag' }]) {
    const ice = signSignal(signalPayload({ type: 'ice', value }), identity); assert.deepEqual(verifySignal(ice, record, network, now).value, value);
  }
  const tampered = { ...decode(envelope), to: 'ee'.repeat(16) };
  assert.throws(() => verifySignal({ ...envelope, payloadBase64: Buffer.from(JSON.stringify(tampered)).toString('base64') }, record, network, now), errorCode('invalid_signature'));
});

test('signal schema rejects unknown fields, unbounded SDP/ICE, nonintegers and unsupported types', () => {
  for (const overrides of [{ seq: 0 }, { seq: 1.1 }, { seq: '1' }, { to: identity.peerId }, { type: 'fetch' }, { value: 'x'.repeat(20001) },
    { value: '🙂'.repeat(6000) }, { type: 'ice', value: {} }, { type: 'ice', value: { candidate: 'x'.repeat(2049), sdpMid: null, sdpMLineIndex: null, usernameFragment: null } },
    { type: 'ice', value: { candidate: '', sdpMid: null, sdpMLineIndex: -1, usernameFragment: null } }, { expiresAt: now + 30001 }, { unknown: true }])
    assert.throws(() => signSignal(signalPayload(overrides), identity));
  assert.throws(() => signSignal(signalPayload(), other), errorCode('invalid_signature'));
});

test('gateway challenge authenticates key possession, nonce, exact origin and signed record bytes', () => {
  const challenge = { nonce: 'aa'.repeat(32), origin: 'https://gateway.example.org', expiresAt: now + 5000 }, record = browser();
  const signature = signChallenge(challenge, record, identity, now);
  assert.equal(verifyChallenge(challenge, record, signature, network, now).peerId, identity.peerId);
  assert.throws(() => verifyChallenge({ ...challenge, nonce: 'bb'.repeat(32) }, record, signature, network, now), errorCode('invalid_signature'));
  assert.throws(() => verifyChallenge(challenge, browser({ browserId: 'ee'.repeat(16) }), signature, network, now), errorCode('invalid_signature'));
  assert.throws(() => verifyChallenge({ ...challenge, origin: 'https://other.example.org' }, record, signature, network, now), errorCode('unsafe_origin'));
  assert.throws(() => verifyChallenge(challenge, record, signature, network, now + 5000), errorCode('stale_challenge'));
  const beyondServerLease = { ...challenge, expiresAt: now + 5001 };
  const clientSignature = signChallenge(beyondServerLease, record, identity, now);
  assert.throws(() => verifyChallenge(beyondServerLease, record, clientSignature, network, now), errorCode('stale_challenge'));
  assert.throws(() => signChallenge(challenge, record, other, now), errorCode('wrong_session'));
});

test('browser challenge signing tolerates bounded clock differences while gateway expiry stays strict', () => {
  const challenge = { nonce: 'aa'.repeat(32), origin: 'https://gateway.example.org', expiresAt: now + 5000 };
  for (const offset of [-10000, -1000, 0, 6000, 10000]) {
    const clientNow = now + offset, record = browser({ issuedAt: clientNow, expiresAt: clientNow + 120000 });
    const signature = signChallenge(challenge, record, identity, clientNow);
    assert.equal(verifyChallenge(challenge, record, signature, network, now).peerId, identity.peerId, `client clock offset ${offset}`);
    assert.throws(() => verifyChallenge(challenge, record, signature, network, now + 5000), errorCode('stale_challenge'));
  }
  const record = browser(), signature = signChallenge(challenge, record, identity, now);
  assert.equal(signChallenge(challenge, record, identity, now - 1000), signature, 'clock tolerance never changes signed bytes');
  assert.equal(signChallenge(challenge, record, identity, now + 6000), signature);
});

test('client challenge tolerance remains finite and does not relax schema or gateway lease checks', () => {
  const challenge = { nonce: 'aa'.repeat(32), origin: 'https://gateway.example.org', expiresAt: now + 5000 }, record = browser();
  for (const expiresAt of [now - 10000, now + 15001, -1, 1.1, '5000'])
    assert.throws(() => signChallenge({ ...challenge, expiresAt }, record, identity, now), errorCode('stale_challenge'));
  assert.throws(() => signChallenge({ ...challenge, issuedAt: now }, record, identity, now), errorCode('invalid_message'));
  for (const expiresAt of [now, now + 5001, now + 15000]) {
    const value = { ...challenge, expiresAt }, signature = signChallenge(value, record, identity, now);
    assert.throws(() => verifyChallenge(value, record, signature, network, now), errorCode('stale_challenge'));
  }
});
